language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: react-performance-test
  api_key:
    secure: GJYicZIX/zHAiqtq+9bQhNqqtXD608UL2eCYtyBxAP0Bz4/llpkG0MZeT/5Ex8qDiad3u9jZHeL+FDr+y0LwjbuzwBBi7HND/jcZ9vtLRR37v52B7fIc5wtkNfSQD6maVx/0zdQJYzWooAKKA9MGAsJSCCM28VBQQ7x3SDauYsTzBrekiN/rJP5ALIu0TxzGDOue4P83IL5ZNJ9nDSJJISFjGRS731+q/GIZB2rmFeONHYFoAXi/8ZokJA1KqHi6iTRIXNq7pZmWlmkMp/R/kBeHuaV+V3JUTpEoFZyIr9svWEATRqAg4cAdRui96jB0qX+eACPgYwUz2DYnKU8thELbgTQlgYNy6rcdvvm0tK1/ulr6KDUdcFIXMKSzrNT1IU8dDrnbRRo5yuVicxZrf9NAm2YQIulFSV74rKNISHFavsZMqWJWQe6VLHqJYGpkPXogkOeSWvBCNl99r4rXPbtJL7yMDzEzn1ADF35y3HT5lbwVLuLYB4AYszOylV/0v8rd/9DTl1EWc1cy+tQYVYrDmhEdcdC7I1Y5uJYMnakkFcQTIrmVxFQmVvgp8BC3cdshLiz34aVkfZMAsPCzu28GI1Kh8JDu8rHtywvp0KjwUs4mirG/kfGkzF2WxrKqv5khEfcAC3q3L2CUOvUlj93IWBnvD6VVrD1Cf1eWof8=
  on:
    repo: Tiico/react-performance-test
    branch: master
