language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: react-performance-test
  api_key:
    secure: e3pacaxX67Lva5nkw/9rvhEkuMjWvr1FI5T3vwTNnGin/rZbJo5+TCv1I7+sWNXM28ph+ImClqY0qwvaMxRudf9SmaJku9M05gjJACTW0t8lWs0Aop7ezTH2jGClV0IDNq3zRSNdzY52RjPfQUUoy5Ga3AQSWv0CQKwyG9ay45Tg5PaBiAwGFAeJzc4v+vtBUDaaFhY4Ha1KEc5386ERwGJimKWkRsFExZaAwRi4UPah0uOMzcV+A6/gKuCT8ZcusTKyCuE+M3TPRnz12gZlqzfOQv71smVuNCSzrXQMbNRp6ox511Xn+/cbvaL9CH5BRa6Ww+8ydrUg7V0INdssfbxm+8s6bip38PP2kpk/is5BMVCLj4ZtDBw5h9w7+vfoppqSAexptX2gOjq+QHEeSJ+TCFGC3lUGrfuqSfjWvcbWbCvLWJjZNLZiZg2XMGwxDo1C2I253dokgl8GDIeGvzp2BTrAHfjABLFVu1iZi2HuE0uI4rFelkJ9R5So8yhZ9E5iGmfjJqThlQ+M4PBXpnXQzPnhQpST1NbbrAcLYiWKnqQXxY7SCBSchi3X46EfDUoIMZ39Zbf/eEPcaSn+2JQK4w6ohoFSpfzCWys1p/OMvWUZ4CYkgHo/uw6VkY/VisGKC2eWurR1uotS7v3pikxqGJCU+ElGjOYKvdhh1co=
  on:
    repo: Tiico/react-performance-test
    branch: master
